name: Daily glymur linux build

on:
  # run daily at 6am IST
  schedule:
    - cron: '30 0 * * *'
  # allow manual runs
  workflow_dispatch:

permissions:
  checks: write # linux.yml
  contents: read # linux.yml
  packages: read # linux.yml
  pull-requests: write # linux.yml

jobs:
  build:
    # don't run cron from forks of the main repository or from other branches
    if: github.repository == 'qualcomm-linux/qcom-deb-images' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/linux.yml
    with:
      kernel_name: glymur
      build_linux_deb_extra_args: '--qcom-next --ref qcom-next-7.1-rc6-20260609  prune.config qcom.config'
      debos_extra_args: '-t dtb:qcom/glymur-crd.dtb'
      # we hardcode the DT, and that's not compatible with the QEMU machine model
      skip_qemu_tests: true
      skip_lava_tests: false
      lava_boards_include: '["glymur-crd"]'
    secrets: inherit
